### ISSUE TITLE
hi ,do you have queue_buffers/unqueue_buffers example ?

### ISSUE THREAD

**Issue by cuu** [stetre/moonal#1]
I just wrote a test use queue_buffers//unqueue_buffers

not sure how to use your code correctly

normally in openal , I can queue a single buf at one time,but your code needs to queue a table

so basicly , I need to insert the single buf into a table first than to use queue_buffers?

**Comment by stetre** [comment]
Hi. Yes, _queue_buffers( )_ accepts a table of buffer objects, and the table may as well contain a single buffer, if you want so.
It's the Lua equivalent to the corresponding C function in openal, that also accepts an array of buffers.

**Comment by cuu** [comment]
thanks for the reply
btw ,
examples/altonegen.lua  line 45:

`srate = tonumber(optarg.s) or 44100`

srate should be a number ,otherwise will have a comparing error
